-- Add gemini_response column to messages table
ALTER TABLE messages
ADD COLUMN IF NOT EXISTS gemini_response TEXT;

-- Add comment to explain the column
COMMENT ON COLUMN messages.gemini_response IS 'Stores the response generated by Gemini AI for this message';

-- Update RLS policies to include gemini_response
CREATE POLICY "Users can view gemini responses from their conversations"
    ON messages
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM conversations
            WHERE conversations.id = messages.conversation_id
            AND conversations.user_id = auth.uid()::text
        )
    );

-- Add index for faster queries on gemini_response
CREATE INDEX IF NOT EXISTS idx_messages_gemini_response ON messages(gemini_response) WHERE gemini_response IS NOT NULL; 